<a href="https://colab.research.google.com/github/trongthuan205/DS102.K21/blob/master/02_MultipleLinearRegression_50_Startups.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 0 . Import library

In [0]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# 1 . Load data

In [2]:
! git clone https://github.com/trongthuan205/DS102.K21 DS102.K21

Cloning into 'DS102.K21'...
remote: Enumerating objects: 99, done.
remote: Counting objects: 100% (99/99), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 232 (delta 56), reused 0 (delta 0), pack-reused 133
Receiving objects: 100% (232/232), 2.31 MiB | 4.45 MiB/s, done.
Resolving deltas: 100% (131/131), done.


In [0]:
data = pd.read_csv('DS102.K21/50_Startups.csv')

In [4]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

# 2 . Preprocessing data

In [0]:
X = np.array(data.iloc[:,0:4].values)
y = np.array(data.iloc[:,-1].values)

In [6]:
ohe_state = np.array(pd.get_dummies(X[:,3]))
ohe_state[0]

array([0, 0, 1], dtype=uint8)

In [7]:
X = np.concatenate((X[:,0:3], ohe_state), axis = 1)
X[0]

array([165349.2, 136897.8, 471784.1, 0, 0, 1], dtype=object)

# 4 . Buid model

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = 0)

In [9]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# 5 . Comapare 

In [0]:
def compare(i_example):
    X = X_test[i_example : i_example + 1]
    y = y_test[i_example]
    y_pred = lin_reg.predict(X)[0]
    print(X, y, y_pred)

In [11]:
for i in range(len(X_test)):
    compare(i)

[[66051.52 182645.56 118148.2 0 1 0]] 103282.38 103015.2015979618
[[100671.96 91790.61 249744.55 1 0 0]] 144259.4 132582.27760815568
[[101913.08 110594.11 229160.95 0 1 0]] 146121.95 132447.7384517448
[[27892.92 84710.77 164470.71 0 1 0]] 77798.83 71976.09851257899
[[153441.51 101145.55 407934.54 0 1 0]] 191050.39 178537.48221055063
[[72107.6 127864.55 353183.81 0 0 1]] 105008.31 116161.24230165101
[[20229.59 65947.93 185265.1 0 0 1]] 81229.06 67851.69209675625
[[61136.38 152701.92 88218.23 0 0 1]] 97483.56 98791.7337468745
[[73994.56 122782.75 303319.26 0 1 0]] 110352.25 113969.43533012444
[[142107.34 91391.77 366168.42 0 1 0]] 166187.94 167921.0656955042
