<a href="https://colab.research.google.com/github/trongthuan205/DS102.K21/blob/master/02_MultipleLinearRegression_50_Startups.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 0 . Import library

In [0]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression

# 1 . Load data

In [2]:
! git clone https://github.com/trongthuan205/DS102.K21 DS102.K21

Cloning into 'DS102.K21'...
remote: Enumerating objects: 134, done.
remote: Counting objects: 100% (134/134), done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 267 (delta 78), reused 0 (delta 0), pack-reused 133
Receiving objects: 100% (267/267), 2.53 MiB | 18.26 MiB/s, done.
Resolving deltas: 100% (153/153), done.


In [0]:
data_train = pd.read_csv('DS102.K21/50_Startups_Train.csv')
data_test = pd.read_csv('DS102.K21/50_Startups_Test.csv')

# 2 . Split data

In [0]:
X_train = data_train.iloc[:,0:5].values
y_train = data_train.iloc[:,-1].values

In [0]:
X_test = data_test.iloc[:,0:5].values
y_test = data_test.iloc[:,-1].values

# 3 . Preprocessing data

In [0]:
ohe_state_train = np.array(pd.get_dummies(X_train[:,-1]))
X_train = np.concatenate((X_train[:,0:3], ohe_state_train), axis = 1)

In [7]:
X_train[0]

array([0, 165349.2, 136897.8, 0, 0, 1], dtype=object)

In [0]:
ohe_state_test = np.array(pd.get_dummies(X_test[:,-1]))
X_test = np.concatenate((X_test[:,0:3], ohe_state_test), axis = 1)

In [9]:
X_test[0]

array([35, 46014.02, 85047.44, 0, 0, 1], dtype=object)

# 4 . Build model

In [10]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# 5 . Evaluate

In [11]:
print(lin_reg.score(X_train, y_train))

0.959970570952373


In [12]:
print(lin_reg.score(X_test, y_test))

0.6654050313360778


# 5 . Compare

In [0]:
def compare(i_example):
    X = X_test[i_example:i_example+1,:]
    y = y_test[i_example]
    y_pred = lin_reg.predict(X)[0]
    print(X, y, y_pred )

In [14]:
for i in range(len(X_test)):
    compare(i)

[[35 46014.02 85047.44 0 0 1]] 96479.51 83324.27351471386
[[36 28663.76 127056.21 0 1 0]] 90708.19 73767.71311156586
[[37 44069.95 51283.14 1 0 0]] 89949.14 84324.76121100728
[[38 20229.59 65947.93 0 0 1]] 81229.06 67219.56247675384
[[39 38558.51 82982.09 1 0 0]] 81005.76 78367.29627815248
[[40 28754.33 118546.05 1 0 0]] 78239.91 71392.30818003064
[[41 27892.92 84710.77 0 1 0]] 77798.83 68285.08537578976
[[42 23640.93 96189.63 1 0 0]] 71498.49 66925.53552066855
[[43 15505.73 127382.3 0 0 1]] 69758.98 57280.134626482475
[[44 22177.74 154806.14 1 0 0]] 65200.33 62349.56977415504
[[45 1000.23 124153.04 0 0 1]] 64926.08 47659.00061714117
[[46 1315.46 115816.21 0 1 0]] 49490.75 48140.56871472594
[[47 0.0 135426.92 1 0 0]] 42559.73 48055.37886358837
[[48 542.05 51743.15 0 0 1]] 35673.41 45494.683835872405
[[49 0.0 116983.8 1 0 0]] 14681.4 46052.49746048982
